/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BApp: typeof import('bootstrap-vue-next/components/BApp')['BApp']
    BBadge: typeof import('bootstrap-vue-next/components/BBadge')['BBadge']
    BCard: typeof import('bootstrap-vue-next/components/BCard')['BCard']
    BCardText: typeof import('bootstrap-vue-next/components/BCard')['BCardText']
    BFormInput: typeof import('bootstrap-vue-next/components/BFormInput')['BFormInput']
    BFormRadio: typeof import('bootstrap-vue-next/components/BFormRadio')['BFormRadio']
    BFormRadioGroup: typeof import('bootstrap-vue-next/components/BFormRadio')['BFormRadioGroup']
    BFormTextarea: typeof import('bootstrap-vue-next/components/BFormTextarea')['BFormTextarea']
    BListGroup: typeof import('bootstrap-vue-next/components/BListGroup')['BListGroup']
    BListGroupItem: typeof import('bootstrap-vue-next/components/BListGroup')['BListGroupItem']
    BModal: typeof import('bootstrap-vue-next/components/BModal')['BModal']
    BOverlay: typeof import('bootstrap-vue-next/components/BOverlay')['BOverlay']
    BProgress: typeof import('bootstrap-vue-next/components/BProgress')['BProgress']
    BTab: typeof import('bootstrap-vue-next/components/BTabs')['BTab']
    BTabs: typeof import('bootstrap-vue-next/components/BTabs')['BTabs']
  }
}
